const ACTION_TYPES = {
  FETCH_ACCOUNT_USERS: "FETCH_ACCOUNT_USERS",
  FETCH_ACCOUNT_USERS_SUCCESS: "FETCH_ACCOUNT_USERS_SUCCESS",
  FETCH_ACCOUNT_USERS_FAIL: "FETCH_ACCOUNT_USERS_FAIL",

  ADD_USER_TO_ACCOUNT: "ADD_USER_TO_ACCOUNT",
  ADD_USER_TO_ACCOUNT_SUCCESS: "ADD_USER_TO_ACCOUNT_SUCCESS",
  ADD_USER_TO_ACCOUNT_FAIL: "ADD_USER_TO_ACCOUNT_FAIL",
};

export default ACTION_TYPES;
