const ACTION_TYPES = {
  FETCH_ACCOUNT_USERS: "FETCH_ACCOUNT_USERS",
  FETCH_ACCOUNT_USERS_SUCCESS: "FETCH_ACCOUNT_USERS_SUCCESS",
  FETCH_ACCOUNT_USERS_FAIL: "FETCH_ACCOUNT_USERS_FAIL",
};

export default ACTION_TYPES;
