const ACTION_TYPES = {
  SUBMIT_TRANSACTION: "SUBMIT_TRANSACTION",
  SUBMIT_FIXED_TRANSACTION_SUCCESS: "SUBMIT_FIXED_TRANSACTION_SUCCESS",
  SUBMIT_ACCOUNT_TRANSACTION_SUCCESS: "SUBMIT_ACCOUNT_TRANSACTION_SUCCESS",
  SUBMIT_TRANSACTION_FAIL: "SUBMIT_TRANSACTION_FAIL",

  EDIT_TRANSACTION: "EDIT_TRANSACTION",
  EDIT_FIXED_TRANSACTION_SUCCESS: "EDIT_FIXED_TRANSACTION_SUCCESS",
  EDIT_ACCOUNT_TRANSACTION_SUCCESS: "EDIT_ACCOUNT_TRANSACTION_SUCCESS",
  EDIT_TRANSACTION_FAIL: "EDIT_TRANSACTION_FAIL",

  DELETE_TRANSACTION: "DELETE_TRANSACTION",
  DELETE_FIXED_TRANSACTION_SUCCESS: "DELETE_FIXED_TRANSACTION_SUCCESS",
  DELETE_ACCOUNT_TRANSACTION_SUCCESS: "DELETE_ACCOUNT_TRANSACTION_SUCCESS",
  DELETE_TRANSACTION_FAIL: "DELETE_TRANSACTION_FAIL",

  FETCH_ALL_FIXED_TRANSACTIONS: "FETCH_ALL_FIXED_TRANSACTIONS",
  FETCH_ALL_FIXED_TRANSACTIONS_SUCCESS: "FETCH_ALL_FIXED_TRANSACTIONS_SUCCESS",
  FETCH_ALL_FIXED_TRANSACTIONS_FAIL: "FETCH_ALL_FIXED_TRANSACTIONS_FAIL",

  FETCH_ALL_ACCOUNT_TRANSACTIONS: "FETCH_ALL_ACCOUNT_TRANSACTIONS",
  FETCH_ALL_ACCOUNT_TRANSACTIONS_SUCCESS:
    "FETCH_ALL_ACCOUNT_TRANSACTIONS_SUCCESS",
  FETCH_ALL_ACCOUNT_TRANSACTIONS_FAIL: "FETCH_ALL_ACCOUNT_TRANSACTIONS_FAIL",
};

export default ACTION_TYPES;
