const ACTION_TYPES = {
  SUBMIT_FIXED_EVENT: "SUBMIT_FIXED_EVENT",
  SUBMIT_FIXED_EVENT_SUCCESS: "SUBMIT_FIXED_EVENT_SUCCESS",
  SUBMIT_FIXED_EVENT_FAIL: "SUBMIT_FIXED_EVENT_FAIL",

  FETCH_ALL_FIXED_EVENTS: "FETCH_ALL_FIXED_EVENTS",
  FETCH_ALL_FIXED_EVENTS_SUCCESS: "FETCH_ALL_FIXED_EVENTS_SUCCESS",
  FETCH_ALL_FIXED_EVENTS_FAIL: "FETCH_ALL_FIXED_EVENTS_FAIL",
};

export default ACTION_TYPES;
