const ACTION_TYPES = {
  FETCH_ALL_FIXED_EVENTS: "FETCH_ALL_FIXED_EVENTS",
  FETCH_ALL_FIXED_EVENTS_SUCCESS: "FETCH_ALL_FIXED_EVENTS_SUCCESS",
  FETCH_ALL_FIXED_EVENTS_FAIL: "FETCH_ALL_FIXED_EVENTS_FAIL",
};

export default ACTION_TYPES;
