const ACTION_TYPES = {
  FETCH_ALL_ACCOUNT_EVENTS: "FETCH_ALL_ACCOUNT_EVENTS",
  FETCH_ALL_ACCOUNT_EVENTS_SUCCESS: "FETCH_ALL_ACCOUNT_EVENTS_SUCCESS",
  FETCH_ALL_ACCOUNT_EVENTS_FAIL: "FETCH_ALL_ACCOUNT_EVENTS_FAIL",
};

export default ACTION_TYPES;
