const ACTION_TYPES = {
  SUBMIT_ACCOUNT_EVENT: "SUBMIT_ACCOUNT_EVENT",
  SUBMIT_ACCOUNT_EVENT_SUCCESS: "SUBMIT_ACCOUNT_EVENT_SUCCESS",
  SUBMIT_ACCOUNT_EVENT_FAIL: "SUBMIT_ACCOUNT_EVENT_FAIL",

  FETCH_ALL_ACCOUNT_EVENTS: "FETCH_ALL_ACCOUNT_EVENTS",
  FETCH_ALL_ACCOUNT_EVENTS_SUCCESS: "FETCH_ALL_ACCOUNT_EVENTS_SUCCESS",
  FETCH_ALL_ACCOUNT_EVENTS_FAIL: "FETCH_ALL_ACCOUNT_EVENTS_FAIL",
};

export default ACTION_TYPES;
